project_id = "lovhzzlmuhjtbblnstfw"

[functions.process-email-queue]
verify_jwt = true

[functions.generate-carousel]
verify_jwt = false

[functions.generate-creative]
verify_jwt = false

[functions.generate-copy]
verify_jwt = false

[functions.create-user-webhook]
verify_jwt = false

[functions.update-user-credit]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false

[functions.create-hotmart-user]
verify_jwt = false

[functions.update-hotmart-user]
verify_jwt = false

[functions.cancel-hotmart-user]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.check-email-available]
verify_jwt = false

[functions.check-whatsapp-available]
verify_jwt = false

[functions.notify-new-user]
verify_jwt = false
